"""make deployment created_at timezone aware

Revision ID: a1aa26e9f218
Revises: eca891b4cee6
Create Date: 2026-09-14 23:44:56.738044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1aa26e9f218'
down_revision: Union[str, Sequence[str], None] = 'eca891b4cee6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
    'deployments',
    'created_at',
    existing_type=sa.DateTime(),
    type_=sa.DateTime(timezone=True),
    existing_nullable=False,
    postgresql_using='created_at::timestamp with time zone'
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('deployments', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
