apiVersion: apps/v1
kind: Deployment
metadata:
  name: forge-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forge-api
  template:
    metadata:
      labels:
        app: forge-api
    spec:
      containers:
        - name: forge-api
          image: forge-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000