apiVersion: apps/v1
kind: Deployment
metadata:
  name: buildkit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: buildkit
  template:
    metadata:
      labels:
        app: buildkit
    spec:
      containers:
        - name: buildkit
          image: moby/buildkit:latest
          args:
            - --addr
            - tcp://0.0.0.0:1234
          ports:
            - containerPort: 1234
          securityContext:
            privileged: true
---
apiVersion: v1
kind: Service
metadata:
  name: buildkit
spec:
  selector:
    app: buildkit
  ports:
    - port: 1234
      targetPort: 1234