apiVersion: v1
kind: Pod
metadata:
  name: buildkit-test
spec:
  restartPolicy: Never
  containers:
    - name: buildctl
      image: moby/buildkit:latest
      command: ["sh", "-c", "sleep 3600"]
      env:
        - name: DOCKER_USERNAME
          valueFrom:
            secretKeyRef:
              name: docker-credentials
              key: DOCKER_USERNAME
        - name: DOCKER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: docker-credentials
              key: DOCKER_PASSWORD